### ISSUE TITLE
Creation of huggingface dataset

### ISSUE THREAD

**Issue by LLukas22** [ASoleimaniB/NLQuAD#1]
Hello, i was using your dataset for a project where i had to switch server often. For convenience i created a copy of NLQuAD on the huggingface hub. This copy is atm publicly available under [LLukas22/NLQuAD](https://huggingface.co/datasets/LLukas22/NLQuAD).

Just wanted to check if this is ok with you. If not i will make the dataset private again for my personal use.

**Comment by ASoleimaniB** [comment]
Thanks for letting me know. That's absolutely fine with me.

**Comment by LLukas22** [comment]
Alright thanks :D
